apiVersion: v1
kind: ServiceAccount
metadata:
  name: desktop-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: desktop-reader
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: desktop-rb
subjects:
- kind: ServiceAccount
  name: desktop-sa
roleRef:
  kind: Role
  name: desktop-reader
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: desktop-hpa
spec: 
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
            #averageUtilization: 50
          averageValue: 7988Mi
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: desktop
