kind: PersistentVolume
apiVersion: v1 
metadata:
  name: desktop-pv 
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-storage
  capacity: 
   storage: 1Gi
  volumeMode: Filesystem
  accessModes: 
   - ReadWriteMany
  nfs:
    server: $(hostname -i)
    path: /mnt/work-related

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: desktop-pvc
spec: 
  volumeName: desktop-pv
  storageClassName: nfs-storage
  resources:
    requests: 
      storage: 1Gi
  accessModes:
    - ReadWriteMany
