apiVersion: v1
kind: ServiceAccount
metadata:
  name: desktop-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: desktop-reader
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: desktop-rb
subjects:
- kind: ServiceAccount
  name: desktop-sa
roleRef:
  kind: Role
  name: desktop-reader
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: desktop-hpa
spec: 
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 5000Mi
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: desktop

---

kind: PersistentVolume
apiVersion: v1 
metadata:
  name: desktop-pv 
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  capacity: 
   storage: 1Gi
  volumeMode: Filesystem
  accessModes: 
   - ReadWriteMany
  nfs:
    server: 10.10.0.11
    path: /mnt/work-related

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: desktop-pvc
spec: 
  volumeName: desktop-pv
  storageClassName: nfs-storage
  resources:
    requests: 
      storage: 1Gi
  accessModes:
    - ReadWriteMany

---
kind: PersistentVolume
apiVersion: v1 
metadata:
  name: jenkins-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  capacity: 
   storage: 1Gi
  volumeMode: Filesystem
  accessModes: 
   - ReadWriteMany
  nfs:
    server: 10.10.0.11
    path: /mnt/jenkins

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc
spec: 
  volumeName: jenkins-pv
  storageClassName: nfs-storage
  resources:
    requests: 
      storage: 1Gi
  accessModes:
    - ReadWriteMany

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: desktop
  labels:
    app: desktop-jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: desktop-jenkins
  template:
    metadata:
      labels:
        app: desktop-jenkins
    spec:
      volumes:
      - name: desktop-pv
        persistentVolumeClaim:
          claimName: desktop-pvc
      - name: jenkins-pv
        persistentVolumeClaim:
          claimName: jenkins-pvc
      containers:
      - name: desktop
        image: volade/desktop:jenkins
        resources:
          limits:
            cpu: 4000m
            memory: 16384Mi
          requests:
            cpu: 3000m
            memory: 8192Mi
        imagePullPolicy: Always
        env:
        - name: VNCPASS
          value: "cart2023!"
        - name: VNCPASSROOT
          value: "caRYBO"
        ports:
        - name: vnc0
          containerPort: 5900
        - name: vnc1  
          containerPort: 5901
        - name: vnc2  
          containerPort: 5902
        - name: vnc3  
          containerPort: 5903
        securityContext:
          privileged: true
        resources:
          requests:
            ephemeral-storage: "1Gi"
        volumeMounts:
        - name: desktop-pv
          mountPath: "/mnt/work-related"
        - name: jenkins-pv
          mountPath: "/var/lib/jenkins"
      - name: novnc
        image: volade/novnc:v3
        ports:
        - name: novnc0
          containerPort: 8080
        - name: novnc1
          containerPort: 8081
        - name: novnc2
          containerPort: 8082
        - name: novnc3
          containerPort: 8083
        resources:
          requests:
            ephemeral-storage: "100Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: desktop
spec:
  type: LoadBalancer
  selector:
    app: desktop-jenkins
  ports:
  - name: novnc0 
    port: 80
    targetPort: novnc0
  - name: novnc1
    port: 81
    targetPort: novnc1
  - name: novnc2
    port: 82
    targetPort: novnc2
  - name: novnc3
    port: 83
    targetPort: novnc3
  loadBalancerIP: 34.31.121.238
