apiVersion: v1
kind: ServiceAccount
metadata:
  name: desktop-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: desktop-reader
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: desktop-rb
  namespace: default
subjects:
- kind: ServiceAccount
  name: desktop-sa
  namespace: default
roleRef:
  kind: Role
  name: desktop-reader
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: desktop-hpa
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageValue: 190Mi
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: desktop