apiVersion: v1
kind: Namespace
metadata:
  name: calico-system

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-ipam-config
data:
  NatOutgoing: "true"

---

apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: default-ipv4-ippool
spec:
  cidr: 172.16.0.0/16
  nat-outgoing: true

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: desktop  # add the 'app' label to the service
  name: desktop
  namespace: default  # change the namespace of the service definition
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080

---

apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: egress-pool
spec:
  cidr: 172.20.0.0/16
  nat-outgoing: true
  ipipMode: Never
  nodeSelector: all()
  disabled: false
  # add the following selector to make the NAT configuration apply only to the 'desktop' service
  selector:
    matchLabels:
      app: desktop
